name: "infra preview & deploy"

on:


  workflow_dispatch:

permissions:
  id-token: write
  contents: read


jobs:
  preview:
    name: "Preview"
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello World"
