name: "z Slack Notify"

on:
  workflow_dispatch:

jobs:
  notify: Slack notify
  runs-on: ubuntu-latest
  steps:
    - name: Slack notify
      uses: slackapi/slack-github-action@v1.23.0
      with:
        channel-id: "C04G3B4Q2RF"
        payload: |
          {
            "attachments": [
              {
                "blocks": [
                  {
                    "type": "header",
                    "text": {
                      "type": "plain_text",
                      "text": "Message Header",
                      "emoji": true
                    }
                  },
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "Hello World :ghost:"
                    }
                  }
                ]
              }
            ]
          }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}